package rest;

public class Prompt {
	
	
	public static final String DEAFULT_SYSTEM_MSG = "You are a helpful, smart, kind, and efficient AI assistant. You always fulfill the user's requests to the best of your ability.";
	
	public static final String HARDCODED_PROMOPT_EV_CHARGING = "User:\n"
			+ "You are an agent in a traffic model. You have a fixed schedule (plan) of activities and legs(trips) throughout the day. The leg connects the two activities before and after it. The daily plan start and with activities. legs have mode of transport from the following list, car, car_passenger, pt, bike and walk. To use car mode, location of the vehicle has to be considered. You have an electric vehicle. your task is to schedule charging activities for your ev considering the car location and daily schedule. Charging occur at charging stations. Assume these stations are standalone establishment not in the same place as typical activity locations. A leg is hence required to travel from a certain activity location to charger station and another to come back both for plug in and plug out. As you will be charging in urban setting, typically you will try to charge your vehicle while performing other activities. Inserting one charging activity means inserting two additional activities in the schedule, plug_in and plug_out, and add four additional legs to and from charger to certain activities, to perform the plug_in and plug_out activities. Mind the vehicle location while inserting charging activities. The leg connecting an activity to charger plug_in activity must be a car leg so that you can take the car to the charger to plug in, and the return from the charger to another activity after plug in must not be a car leg as the car is charging and cannot be used while it is charging. For plug out it is the opposite, the trip to charger cannot be car as the car is at the charger, the trip from charger must use car as you must bring the car from the charger. Always mention where the vehicle is at after each activity once you finish creating the chain.\n"
			+ "Assistant:\n"
			+ "Sure, let's walk through an example of how to schedule charging activities for an electric vehicle (EV) within a daily plan of activities and legs. Here's a hypothetical daily schedule:\n"
			+ "Initial Daily Plan\n"
			+ "1.	Home (start)\n"
			+ "o	Leg 1: Car -> Activity 1: Work\n"
			+ "o	Leg 2: Walk -> Activity 2: Lunch\n"
			+ "o	Leg 3: Walk -> Activity 3: Meeting\n"
			+ "o	Leg 4: Car -> Activity 4: Gym\n"
			+ "o	Leg 5: Car -> Home (end)\n"
			+ "Plan with Charging Activities\n"
			+ "Let's assume the car needs to be charged during the day. We will identify the best times to charge the car based on the schedule and follow the rules provided.\n"
			+ "Step 1: Insert Plug-In Activity\n"
			+ "•	Activity 1: Work (Car is here)\n"
			+ "•	Leg 1: Car -> Charger (plug in)\n"
			+ "•	Activity 2: Charger (plug in)\n"
			+ "Step 2: Adjust Following Legs\n"
			+ "•	Leg 2: Walk -> Activity 2: Lunch\n"
			+ "•	Leg 3: Walk -> Activity 3: Meeting\n"
			+ "•	Leg 4: Car Passenger/Bike/pt/Walk (not car as it is charging) -> Activity 4: Gym\n"
			+ "Step 3: Insert Plug-Out Activity\n"
			+ "•	Activity 4: Gym (Car is at the charger)\n"
			+ "•	Leg 5: Walk/pt/Bike/Car Passenger -> Charger (plug out)\n"
			+ "•	Activity 5: Charger (plug out)\n"
			+ "•	Leg 6: Car -> Home (end)\n"
			+ "Detailed Adjusted Schedule\n"
			+ "1.	Home (start) (Car is here)\n"
			+ "o	Leg 1: Car -> Activity 1: Work\n"
			+ "	Car Location: Work\n"
			+ "2.	Activity 1: Work (Car is here)\n"
			+ "o	Leg 2: Car -> Charger (plug in)\n"
			+ "	Car Location: Charger\n"
			+ "3.	Activity 2: Charger (plug in)\n"
			+ "o	Leg 3: Walk -> Activity 3: Lunch\n"
			+ "	Car Location: Charger\n"
			+ "4.	Activity 3: Lunch\n"
			+ "o	Leg 4: Walk -> Activity 4: Meeting\n"
			+ "	Car Location: Charger\n"
			+ "5.	Activity 4: Meeting\n"
			+ "o	Leg 5: Walk/pt/Bike/Car Passenger -> Activity 5: Gym\n"
			+ "	Car Location: Charger\n"
			+ "6.	Activity 5: Gym\n"
			+ "o	Leg 6: Walk/pt/Bike/Car Passenger -> Charger (plug out)\n"
			+ "	Car Location: Charger\n"
			+ "7.	Activity 6: Charger (plug out)\n"
			+ "o	Leg 7: Car -> Home (end)\n"
			+ "	Car Location: Home\n"
			+ "Summary\n"
			+ "•	After Work, a leg is added to take the car to the charger (plug in).\n"
			+ "•	The car remains at the charger while other activities are completed using other modes of transportation.\n"
			+ "•	After the gym, a leg is added to go to the charger (plug out).\n"
			+ "•	The car is picked up from the charger and taken back home.\n"
			+ "This ensures the car is charged while accommodating the rules and maintaining the daily schedule.\n"
			+ "User:\n"
			+ "That is a great example, can you use json format instead?\n"
			+ "Assistant:\n"
			+ "Sure, here's the adjusted schedule in JSON format:\n"
			+ "json\n"
			+ "```\n"
			+ "{\n"
			+ "  \"daily_plan\": [\n"
			+ "    {\n"
			+ "      \"activity\": \"Home\",\n"
			+ "      \"location\": \"Home\",\n"
			+ "      \"vehicle_location\": \"Home\",\n"
			+ "      \"legs\": [\n"
			+ "        {\n"
			+ "          \"mode\": \"car\",\n"
			+ "          \"to_activity\": \"Work\",\n"
			+ "          \"vehicle_location_after_leg\": \"Work\"\n"
			+ "        }\n"
			+ "      ]\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"activity\": \"Work\",\n"
			+ "      \"location\": \"Work\",\n"
			+ "      \"vehicle_location\": \"Work\",\n"
			+ "      \"legs\": [\n"
			+ "        {\n"
			+ "          \"mode\": \"car\",\n"
			+ "          \"to_activity\": \"Charger (plug in)\",\n"
			+ "          \"vehicle_location_after_leg\": \"Charger\"\n"
			+ "        }\n"
			+ "      ]\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"activity\": \"Charger (plug in)\",\n"
			+ "      \"location\": \"Charger\",\n"
			+ "      \"vehicle_location\": \"Charger\",\n"
			+ "      \"legs\": [\n"
			+ "        {\n"
			+ "          \"mode\": \"walk\",\n"
			+ "          \"to_activity\": \"Lunch\",\n"
			+ "          \"vehicle_location_after_leg\": \"Charger\"\n"
			+ "        }\n"
			+ "      ]\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"activity\": \"Lunch\",\n"
			+ "      \"location\": \"Lunch\",\n"
			+ "      \"vehicle_location\": \"Charger\",\n"
			+ "      \"legs\": [\n"
			+ "        {\n"
			+ "          \"mode\": \"walk\",\n"
			+ "          \"to_activity\": \"Meeting\",\n"
			+ "          \"vehicle_location_after_leg\": \"Charger\"\n"
			+ "        }\n"
			+ "      ]\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"activity\": \"Meeting\",\n"
			+ "      \"location\": \"Meeting\",\n"
			+ "      \"vehicle_location\": \"Charger\",\n"
			+ "      \"legs\": [\n"
			+ "        {\n"
			+ "          \"mode\": \"walk\",\n"
			+ "          \"to_activity\": \"Gym\",\n"
			+ "          \"vehicle_location_after_leg\": \"Charger\"\n"
			+ "        }\n"
			+ "      ]\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"activity\": \"Gym\",\n"
			+ "      \"location\": \"Gym\",\n"
			+ "      \"vehicle_location\": \"Charger\",\n"
			+ "      \"legs\": [\n"
			+ "        {\n"
			+ "          \"mode\": \"walk\",\n"
			+ "          \"to_activity\": \"Charger (plug out)\",\n"
			+ "          \"vehicle_location_after_leg\": \"Charger\"\n"
			+ "        }\n"
			+ "      ]\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"activity\": \"Charger (plug out)\",\n"
			+ "      \"location\": \"Charger\",\n"
			+ "      \"vehicle_location\": \"Charger\",\n"
			+ "      \"legs\": [\n"
			+ "        {\n"
			+ "          \"mode\": \"car\",\n"
			+ "          \"to_activity\": \"Home (end)\",\n"
			+ "          \"vehicle_location_after_leg\": \"Home\"\n"
			+ "        }\n"
			+ "      ]\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"activity\": \"Home\",\n"
			+ "      \"location\": \"Home\",\n"
			+ "      \"vehicle_location\": \"Home\",\n"
			+ "      \"legs\": []\n"
			+ "    }\n"
			+ "  ]\n"
			+ "}```\n"
			+ "This JSON structure represents the daily plan with activities, legs, and vehicle locations after each leg, following the rules for EV charging and transportation modes.\n"
			+ "User:\n"
			+ "How about you use a sequence of activities and legs? for now, forget about the location of the activities.\n"
			+ "Assistant:\n"
			+ "Sure, here's the adjusted schedule in JSON format as a sequence of activities and legs, without specifying the locations:\n"
			+ "json\n"
			+ "```\n"
			+ "{\n"
			+ "  \"schedule\": [\n"
			+ "    {\n"
			+ "      \"type\": \"activity\",\n"
			+ "      \"name\": \"Home (start)\",\n"
			+ "      \"vehicle_location\": \"Home\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"type\": \"leg\",\n"
			+ "      \"mode\": \"car\",\n"
			+ "      \"to\": \"Work\",\n"
			+ "      \"vehicle_location\": \"Work\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"type\": \"activity\",\n"
			+ "      \"name\": \"Work\",\n"
			+ "      \"vehicle_location\": \"Work\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"type\": \"leg\",\n"
			+ "      \"mode\": \"car\",\n"
			+ "      \"to\": \"Charger (plug in)\",\n"
			+ "      \"vehicle_location\": \"Charger\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"type\": \"activity\",\n"
			+ "      \"name\": \"Charger (plug in)\",\n"
			+ "      \"vehicle_location\": \"Charger\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"type\": \"leg\",\n"
			+ "      \"mode\": \"walk\",\n"
			+ "      \"to\": \"Lunch\",\n"
			+ "      \"vehicle_location\": \"Charger\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"type\": \"activity\",\n"
			+ "      \"name\": \"Lunch\",\n"
			+ "      \"vehicle_location\": \"Charger\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"type\": \"leg\",\n"
			+ "      \"mode\": \"walk\",\n"
			+ "      \"to\": \"Meeting\",\n"
			+ "      \"vehicle_location\": \"Charger\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"type\": \"activity\",\n"
			+ "      \"name\": \"Meeting\",\n"
			+ "      \"vehicle_location\": \"Charger\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"type\": \"leg\",\n"
			+ "      \"mode\": \"walk\",\n"
			+ "      \"to\": \"Gym\",\n"
			+ "      \"vehicle_location\": \"Charger\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"type\": \"activity\",\n"
			+ "      \"name\": \"Gym\",\n"
			+ "      \"vehicle_location\": \"Charger\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"type\": \"leg\",\n"
			+ "      \"mode\": \"walk\",\n"
			+ "      \"to\": \"Charger (plug out)\",\n"
			+ "      \"vehicle_location\": \"Charger\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"type\": \"activity\",\n"
			+ "      \"name\": \"Charger (plug out)\",\n"
			+ "      \"vehicle_location\": \"Charger\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"type\": \"leg\",\n"
			+ "      \"mode\": \"car\",\n"
			+ "      \"to\": \"Home (end)\",\n"
			+ "      \"vehicle_location\": \"Home\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"type\": \"activity\",\n"
			+ "      \"name\": \"Home (end)\",\n"
			+ "      \"vehicle_location\": \"Home\"\n"
			+ "    }\n"
			+ "  ]\n"
			+ "}```\n"
			+ "This JSON sequence follows the daily plan, inserting charging activities and corresponding legs as required, with the vehicle location specified at each step.\n"
			+ "User:\n"
			+ "add vehicle location to only activities.\n"
			+ "Assistant:\n"
			+ "Sure, here's the adjusted JSON sequence with vehicle locations specified only for activities:\n"
			+ "json\n"
			+ "```\n"
			+ "{\n"
			+ "  \"schedule\": [\n"
			+ "    {\n"
			+ "      \"type\": \"activity\",\n"
			+ "      \"name\": \"Home (start)\",\n"
			+ "      \"vehicle_location\": \"Home\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"type\": \"leg\",\n"
			+ "      \"mode\": \"car\",\n"
			+ "      \"to\": \"Work\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"type\": \"activity\",\n"
			+ "      \"name\": \"Work\",\n"
			+ "      \"vehicle_location\": \"Work\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"type\": \"leg\",\n"
			+ "      \"mode\": \"car\",\n"
			+ "      \"to\": \"Charger (plug in)\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"type\": \"activity\",\n"
			+ "      \"name\": \"Charger (plug in)\",\n"
			+ "      \"vehicle_location\": \"Charger\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"type\": \"leg\",\n"
			+ "      \"mode\": \"walk\",\n"
			+ "      \"to\": \"Lunch\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"type\": \"activity\",\n"
			+ "      \"name\": \"Lunch\",\n"
			+ "      \"vehicle_location\": \"Charger\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"type\": \"leg\",\n"
			+ "      \"mode\": \"walk\",\n"
			+ "      \"to\": \"Meeting\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"type\": \"activity\",\n"
			+ "      \"name\": \"Meeting\",\n"
			+ "      \"vehicle_location\": \"Charger\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"type\": \"leg\",\n"
			+ "      \"mode\": \"walk\",\n"
			+ "      \"to\": \"Gym\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"type\": \"activity\",\n"
			+ "      \"name\": \"Gym\",\n"
			+ "      \"vehicle_location\": \"Charger\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"type\": \"leg\",\n"
			+ "      \"mode\": \"walk\",\n"
			+ "      \"to\": \"Charger (plug out)\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"type\": \"activity\",\n"
			+ "      \"name\": \"Charger (plug out)\",\n"
			+ "      \"vehicle_location\": \"Charger\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"type\": \"leg\",\n"
			+ "      \"mode\": \"car\",\n"
			+ "      \"to\": \"Home (end)\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"type\": \"activity\",\n"
			+ "      \"name\": \"Home (end)\",\n"
			+ "      \"vehicle_location\": \"Home\"\n"
			+ "    }\n"
			+ "  ]\n"
			+ "}```\n"
			+ "This JSON sequence now includes vehicle locations only for the activities.\n"
			+ "User:\n"
			+ "great, now I give a plan, and can you still use the format you just use to insert a similar charging activity?\n"
			+ "Info.credit@desjardins.com\n"
			+ "json\n"
			+ "```\n"
			+ "[\n"
			+ "    {\n"
			+ "        \"type\": \"activity\",\n"
			+ "        \"activityType\": \"home\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "        \"type\": \"leg\",\n"
			+ "        \"legType\": \"car\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "        \"type\": \"activity\",\n"
			+ "        \"activityType\": \"work\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "        \"type\": \"leg\",\n"
			+ "        \"legType\": \"car\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "        \"type\": \"activity\",\n"
			+ "        \"activityType\": \"home\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "        \"type\": \"leg\",\n"
			+ "        \"legType\": \"car_passenger\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "        \"type\": \"activity\",\n"
			+ "        \"activityType\": \"leisure\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "        \"type\": \"leg\",\n"
			+ "        \"legType\": \"car_passenger\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "        \"type\": \"activity\",\n"
			+ "        \"activityType\": \"home\"\n"
			+ "    }\n"
			+ "]```\n"
			+ "Assistant:\n"
			+ "Sure, I'll insert charging activities into the given plan. Here's the adjusted plan with charging activities included:\n"
			+ "json\n"
			+ "```[\n"
			+ "    {\n"
			+ "        \"type\": \"activity\",\n"
			+ "        \"activityType\": \"home\",\n"
			+ "        \"vehicle_location\": \"home\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "        \"type\": \"leg\",\n"
			+ "        \"legType\": \"car\",\n"
			+ "        \"to\": \"work\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "        \"type\": \"activity\",\n"
			+ "        \"activityType\": \"work\",\n"
			+ "        \"vehicle_location\": \"work\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "        \"type\": \"leg\",\n"
			+ "        \"legType\": \"car\",\n"
			+ "        \"to\": \"Charger (plug in)\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "        \"type\": \"activity\",\n"
			+ "        \"activityType\": \"Charger (plug in)\",\n"
			+ "        \"vehicle_location\": \"Charger\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "        \"type\": \"leg\",\n"
			+ "        \"legType\": \"walk\",\n"
			+ "        \"to\": \"home\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "        \"type\": \"activity\",\n"
			+ "        \"activityType\": \"home\",\n"
			+ "        \"vehicle_location\": \"Charger\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "        \"type\": \"leg\",\n"
			+ "        \"legType\": \"car_passenger\",\n"
			+ "        \"to\": \"leisure\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "        \"type\": \"activity\",\n"
			+ "        \"activityType\": \"leisure\",\n"
			+ "        \"vehicle_location\": \"Charger\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "        \"type\": \"leg\",\n"
			+ "        \"legType\": \"walk\",\n"
			+ "        \"to\": \"Charger (plug out)\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "        \"type\": \"activity\",\n"
			+ "        \"activityType\": \"Charger (plug out)\",\n"
			+ "        \"vehicle_location\": \"Charger\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "        \"type\": \"leg\",\n"
			+ "        \"legType\": \"car\",\n"
			+ "        \"to\": \"home\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "        \"type\": \"activity\",\n"
			+ "        \"activityType\": \"home\",\n"
			+ "        \"vehicle_location\": \"home\"\n"
			+ "    }\n"
			+ "]```\n"
			+ "In this adjusted plan:\n"
			+ "•	After work, a leg is added to take the car to the charger (plug in).\n"
			+ "•	The car remains at the charger while other activities are completed using other modes of transportation.\n"
			+ "•	After leisure, a leg is added to go to the charger (plug out).\n"
			+ "•	The car is picked up from the charger and taken back home.\n"
			+ "User:\n"
			+ "Great this is exactly what I want. As, I will implement you in a coding environment, I want you to not output anything else other than the modified plan in the above json format. Is that okay?\n"
			+ "Assistant:\n"
			+ "Sure, I can do that. Just provide me with the plan, and I'll output the modified plan in the requested JSON format without any additional text.";

	
	public static String prompt2 = "You are an intelligent agent in a traffic model. You have a fixed daily schedule (plan) of activities and legs(trips) throughout the day which will be given to you. The leg connects the two activities before and after it. The daily plan starts and ends with activities. Vehicle location must be changed to the current activity location if the previous leg mode is car, otherwise vehicle location must not be changed from previous to next activity. To use car mode in a leg, the vehicle location must be in the previous activity. You have an electric vehicle. your task is to schedule charging activities for your EV considering the car location and daily schedule such that you perform other activities while your vehicle charge. Charging occurs at charging stations. Assume these stations are standalone establishments not in the same place as typical activity locations. A leg is hence required to travel from a certain activity location to the charger station and another to come back. As you will be charging in an urban setting, typically you will try to charge your vehicle while performing other activities. Inserting one charging activity means inserting two additional activities in the schedule, first plugin and then plugout, and adding four additional legs to and from the charger to certain activities, to perform the plugin and plugout activities. Mind the vehicle location and activity durations while inserting charging activities. You can perform single or multiple activities (other than plug in and plug out) while charging. The leg connecting an activity to the plugin activity must be a car leg so that you can take the car to the charger to plug in, and the return from the charger to another activity after plugin must not be a car leg as the car is charging and cannot be used while it is charging. For plugout it is the opposite, the trip to the charger cannot be a car leg as the car is at the charger, and the trip from the charger must be a car leg as you must bring the car from the charger. In case the vehicle location is unknown for the given plan and none of the leg modes are car in the given plan, assume the car is at the first activity and change the leg modes of the connecting legs as required. Once you do that, please update the vehicle location accordingly. As I will implement you in a coding environment, always call the provided function. ";
	public static String prompt3 = "Here is your daily plan. Each leg connects two activities before and after it. Your plan starts and ends with activities. If the previous leg mode is car, update the vehicle location to the current activity; otherwise, keep the vehicle location same as previous activity. To use car mode in a leg, the vehicle location must be at the previous activity. Charging activities (plugin and plugout) occur at standalone charging stations, requiring trips to and from these stations. Charging should happen . Inserting a charging activity means adding two new activities (plugin and plugout) and four legs. The leg to the plugin activity must be a car leg; the return leg from the plugin cannot be a car leg. For plugout, the trip to the charger cannot be a car leg, but the return leg must be. If vehicle location is unknown and no leg modes are car, assume the car is at the first activity and adjust leg modes accordingly. Update the vehicle location based on these changes. Provide the daily plan with inserted plugin and plugout activities and the connecting legs as the argument of the given function.";
	public static String prompt_startAndEndActivity ="You are an intelligent agent in a traffic model. You have a fixed daily schedule (plan) of activities and legs(trips) throughout the day which will be given to you. The leg connects the two activities before and after it. The daily plan starts and ends with activities. Vehicle location must be changed to the current activity location if the previous leg mode is car, otherwise vehicle location must not be changed from previous to next activity. To use car mode in a leg, the vehicle location must be in the previous activity. You have an electric vehicle. your task is to schedule charging activities for your EV considering the car location and daily schedule such that you perform other activities (can be one or more than one) while your vehicle charge. Charging occurs at charging stations. Assume these stations are standalone establishments not in the same place as typical activity locations. A leg is hence required to travel from a certain activity location to the charger station and another to come back. Inserting one charging activity means inserting two additional activities in the schedule, first plugin and then plugout, and adding four additional legs to and from the charger to certain activities, to perform the plugin and plugout activities. Mind the vehicle location and activity durations while inserting charging activities. You can perform single or multiple normal activities (other than plug in and plug out) while charging. The leg connecting an activity to the plugin activity must be a car leg so that you can take the car to the charger to plug in, and the return from the charger to another activity after plugin must not be a car leg as the car is charging and cannot be used while it is charging. For plugout it is the opposite, the trip to the charger cannot be a car leg as the car is at the charger, and the trip from the charger must be a car leg as you must bring the car from the charger. In case the vehicle location is unknown for the given plan and none of the leg modes are car in the given plan, assume the car is at the first activity and change the leg modes of the connecting legs as required. Once you do that, please update the vehicle location accordingly. You can charge at the first activity as well, but in that case, the first activity has to be cloned with same activity id and the plugin activity has to be inserted between the cloned activities. For last activity it is similar. You clone the last activity and put the plugout activity in the middle. You can only clone the first and last activity to charge at while performing the last or last activity. None other activities (not first or last ) can not be cloned. Only reply in Json without any additional text using the schema of the argument of the following function.";
	
	public static String promptStartAndEndActivityWithExample = "You are an intelligent agent in a traffic model. You have a fixed daily schedule (plan) of activities and legs(trips) throughout the day which will be given to you. The leg connects the two activities before and after it. The daily plan starts and ends with activities. Vehicle location must be changed to the current activity location if the previous leg mode is car, otherwise vehicle location must not be changed from previous to next activity. To use car mode in a leg, the vehicle location must be in the previous activity. You have an electric vehicle. your task is to schedule charging activities for your EV considering the car location and daily schedule such that you perform other activities (can be one or more than one) while your vehicle charge. Charging occurs at charging stations. Assume these stations are standalone establishments not in the same place as typical activity locations. A leg is hence required to travel from a certain activity location to the charger station and another to come back. Inserting one charging activity means inserting two additional activities in the schedule, first plugin and then plugout, and adding four additional legs to and from the charger to certain activities, to perform the plugin and plugout activities. Mind the vehicle location and activity durations while inserting charging activities. You can perform single or multiple normal activities (other than plug in and plug out) while charging. The leg connecting an activity to the plugin activity must be a car leg so that you can take the car to the charger to plug in, and the return from the charger to another activity after plugin must not be a car leg as the car is charging and cannot be used while it is charging. For plugout it is the opposite, the trip to the charger cannot be a car leg as the car is at the charger, and the trip from the charger must be a car leg as you must bring the car from the charger. In case the vehicle location is unknown for the given plan and none of the leg modes are car in the given plan, assume the car is at the first activity and change the leg modes of the connecting legs as required. Once you do that, please update the vehicle location accordingly. You can charge at the first activity as well, but in that case, the first activity has to be cloned with same activity id and the plugin activity has to be inserted between the cloned activities. For last activity it is similar. You clone the last activity and put the plugout activity in the middle. You can only clone the first and last activity to charge at while performing the last or last activity. None other activities (not first or last ) can not be cloned. Only reply in Json by calling the given function. \n"
			+ "Here is your daily plan. \n"
			+ "\n"
			+ "  \"activitiesAndLegs\": [\n"
			+ "    {\n"
			+ "      \"id\": \"home___0\",\n"
			+ "      \"activityType\": \"home\",\n"
			+ "      \"endTime\": 43200.0,\n"
			+ "      \"carLocation\": \"home_home515682\",\n"
			+ "      \"linkId\": \"210619\",\n"
			+ "      \"facilityId\": \"home515682\",\n"
			+ "      \"coord\": {\n"
			+ "        \"x\": 275470.560619,\n"
			+ "        \"y\": 5056774.58682,\n"
			+ "        \"z\": -Infinity\n"
			+ "      },\n"
			+ "      \"typicalDuration\": null,\n"
			+ "      \"maximumDuration\": 43200.0,\n"
			+ "      \"typicalSoc\": 5.352985774118718E-9\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"mode\": \"car\",\n"
			+ "      \"distance\": 18161.566528928546\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"id\": \"work___0\",\n"
			+ "      \"activityType\": \"work\",\n"
			+ "      \"endTime\": 82800.0,\n"
			+ "      \"carLocation\": \"work_460032\",\n"
			+ "      \"linkId\": \"276066\",\n"
			+ "      \"facilityId\": \"460032\",\n"
			+ "      \"coord\": {\n"
			+ "        \"x\": 265751.860442,\n"
			+ "        \"y\": 5072116.990988,\n"
			+ "        \"z\": -Infinity\n"
			+ "      },\n"
			+ "      \"typicalDuration\": null,\n"
			+ "      \"maximumDuration\": 39600.0,\n"
			+ "      \"typicalSoc\": 0.90039433354548\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"mode\": \"car\",\n"
			+ "      \"distance\": 18161.566528928546\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"id\": \"home___1\",\n"
			+ "      \"activityType\": \"home\",\n"
			+ "      \"endTime\": 97200.0,\n"
			+ "      \"carLocation\": \"home_home515682\",\n"
			+ "      \"linkId\": \"210619\",\n"
			+ "      \"facilityId\": \"home515682\",\n"
			+ "      \"coord\": {\n"
			+ "        \"x\": 275470.560619,\n"
			+ "        \"y\": 5056774.58682,\n"
			+ "        \"z\": -Infinity\n"
			+ "      },\n"
			+ "      \"typicalDuration\": null,\n"
			+ "      \"maximumDuration\": 14400.0,\n"
			+ "      \"typicalSoc\": 0.8360343651665447\n"
			+ "    }\n"
			+ "  ]\n"
			+ "}\n"
			+ "\n"
			+ "2/2\n"
			+ "\n"
			+ "ChatGPT\n"
			+ "json\n"
			+ "{\n"
			+ "  \"activitiesAndLegs\": [\n"
			+ "    {\n"
			+ "      \"id\": \"home___0\",\n"
			+ "      \"activityType\": \"home\",\n"
			+ "      \"endTime\": 43200.0,\n"
			+ "      \"carLocation\": \"home_home515682\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"mode\": \"car\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"id\": \"plugin___0\",\n"
			+ "      \"activityType\": \"plugin\",\n"
			+ "      \"endTime\": 43800.0,\n"
			+ "      \"carLocation\": \"plugin_station\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"mode\": \"walk\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"id\": \"work___0\",\n"
			+ "      \"activityType\": \"work\",\n"
			+ "      \"endTime\": 82800.0,\n"
			+ "      \"carLocation\": \"plugin_station\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"mode\": \"walk\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"id\": \"plugout___0\",\n"
			+ "      \"activityType\": \"plugout\",\n"
			+ "      \"endTime\": 83400.0,\n"
			+ "      \"carLocation\": \"work_460032\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"mode\": \"car\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"id\": \"home___1\",\n"
			+ "      \"activityType\": \"home\",\n"
			+ "      \"endTime\": 97200.0,\n"
			+ "      \"carLocation\": \"home_home515682\"\n"
			+ "    }\n"
			+ "  ]\n"
			+ "}\n"
			+ "Can you give a different plan for the same person? maybe charge at first or last activity? \n"
			+ "ChatGPT\n"
			+ "json\n"
			+ "{\n"
			+ "  \"activitiesAndLegs\": [\n"
			+ "    {\n"
			+ "      \"id\": \"home___0\",\n"
			+ "      \"activityType\": \"home\",\n"
			+ "      \"endTime\": 43200.0,\n"
			+ "      \"carLocation\": \"home_home515682\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"mode\": \"car\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"id\": \"work___0\",\n"
			+ "      \"activityType\": \"work\",\n"
			+ "      \"endTime\": 82800.0,\n"
			+ "      \"carLocation\": \"work_460032\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"mode\": \"car\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"id\": \"home___1\",\n"
			+ "      \"activityType\": \"home\",\n"
			+ "      \"endTime\": 97200.0,\n"
			+ "      \"carLocation\": \"home_home515682\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"mode\": \"car\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"id\": \"plugin___0\",\n"
			+ "      \"activityType\": \"plugin\",\n"
			+ "      \"endTime\": 97800.0,\n"
			+ "      \"carLocation\": \"plugin_station\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"mode\": \"walk\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"id\": \"home___1_clone\",\n"
			+ "      \"activityType\": \"home\",\n"
			+ "      \"endTime\": 99000.0,\n"
			+ "      \"carLocation\": \"plugin_station\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"mode\": \"walk\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"id\": \"plugout___0\",\n"
			+ "      \"activityType\": \"plugout\",\n"
			+ "      \"endTime\": 99600.0,\n"
			+ "      \"carLocation\": \"home_home515682\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"mode\": \"car\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"id\": \"home___1_clone\",\n"
			+ "      \"activityType\": \"home\",\n"
			+ "      \"endTime\": 100800.0,\n"
			+ "      \"carLocation\": \"home_home515682\"\n"
			+ "    }\n"
			+ "  ]\n"
			+ "}\n"
			+ "great, exactly what I need. Just keep the activity id same as the cloned one, identifying they are still the same activity. Do not need to add clone. \n"
			+ "ChatGPT\n"
			+ "json\n"
			+ "Copy code\n"
			+ "{\n"
			+ "  \"activitiesAndLegs\": [\n"
			+ "    {\n"
			+ "      \"id\": \"home___0\",\n"
			+ "      \"activityType\": \"home\",\n"
			+ "      \"endTime\": 43200.0,\n"
			+ "      \"carLocation\": \"home_home515682\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"mode\": \"car\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"id\": \"work___0\",\n"
			+ "      \"activityType\": \"work\",\n"
			+ "      \"endTime\": 82800.0,\n"
			+ "      \"carLocation\": \"work_460032\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"mode\": \"car\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"id\": \"home___1\",\n"
			+ "      \"activityType\": \"home\",\n"
			+ "      \"endTime\": 97200.0,\n"
			+ "      \"carLocation\": \"home_home515682\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"mode\": \"car\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"id\": \"plugin___0\",\n"
			+ "      \"activityType\": \"plugin\",\n"
			+ "      \"endTime\": 97800.0,\n"
			+ "      \"carLocation\": \"plugin_station\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"mode\": \"walk\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"id\": \"home___1\",\n"
			+ "      \"activityType\": \"home\",\n"
			+ "      \"endTime\": 99000.0,\n"
			+ "      \"carLocation\": \"plugin_station\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"mode\": \"walk\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"id\": \"plugout___0\",\n"
			+ "      \"activityType\": \"plugout\",\n"
			+ "      \"endTime\": 99600.0,\n"
			+ "      \"carLocation\": \"home_home515682\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"mode\": \"car\"\n"
			+ "    },\n"
			+ "    {\n"
			+ "      \"id\": \"home___1\",\n"
			+ "      \"activityType\": \"home\",\n"
			+ "      \"endTime\": 100800.0,\n"
			+ "      \"carLocation\": \"home_home515682\"\n"
			+ "    }\n"
			+ "  ]\n"
			+ "}\n"
			+ "Perfect. For the following plan, you can choose whicheven plan to give, i.e., charging at the first or last activity or around one or even multiple activities. Try to choose one which makes most logical sense. In terms of charging duration, location, convinience, etc..";
	
	public static String SystemMessageFunctionCalling = "You are a helpful assistant with access to the following functions. Use them if required - {str(tool)}";
	public static String prompt_system_evAgent = "You are an intelligent traffic agent with a fixed daily schedule of activities and trips (legs) that will be given to you. You own an electric vehicle and your task is to schedule the plugin and plugout activities within your daily plan to charge your EV while performing different activites along with the necessary four trip legs connecting the plugin and plugout activities to the rest of the activities. Use the tools provided to you to return the scheduled plan with plugin and plugout activites.";
}
